#!/usr/bin/env bash

cd "$(dirname "$0")" || exit

for y in $(find aoc* -name "day*" -type d \
            | cut -c 4-7 \
            | sort -un); do
    ds=$(find aoc$y -name "day*" -type d \
        | cut -d / -f 2 \
        | cut -c 4- \
        | sort -n)
    aoc --timeout 15 \
        --no-submit \
        --years $y \
        --days $ds
done
