#!/usr/bin/env bash

cd "$(dirname "$0")" || exit

function doit() {
    aoc --timeout 30 \
            "$@" \
            || (echo;echo -e "\033[31mOOPS"'!'"\033[0m";echo)
}

if [ "$1" = "--all" ] || [ "$1" = "-a" ]; then
    for y in $(find aoc* -name "day*" -type d \
                | cut -c 4-7 \
                | sort -unr); do
        ds=$(find aoc$y -name "__init__.py" \
            | grep '/day' \
            | cut -d / -f 2 \
            | cut -c 4- \
            | sort -nr)
        doit --years $y --days $ds
    done
elif [ "$1" != "" ]; then
    doit "$@"
    exit
else
    # doit $(date -v+3H +' -y 20%y -d %d')
    echo "AoC's over; there is no current day. Try '$0 -y 2023 -d 7' or '$0 --all')"
    exit 1
fi
