#!/usr/bin/env bash

cd "$(dirname "$0")" || exit

for y in $(find aoc* -name "day*" -type d \
            | cut -c 4-7 \
            | sort -unr); do
    ds=$(find aoc$y -name "__init__.py" \
        | grep '/day' \
        | cut -d / -f 2 \
        | cut -c 4- \
        | sort -nr)
    aoc --timeout 15 \
        --years $y \
        --days $ds \
        "$@" \
        || (echo;echo -e "\033[31mOOPS"'!'"\033[0m";echo)
done
