name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11.1
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1
          cache: 'pip'
      - name: Install Python Dependencies
        working-directory: ./python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test Python
        working-directory: ./python
        env:
          PYTHONPATH: .
        run: pytest
      - name: No Dirtiness, Python!
        run: git diff --exit-code
      - name: Black Check
        uses: psf/black@stable

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - name: Download Java Dependencies
        run: ./mvnw -B dependency:go-offline
      - name: Build Java
        run: ./mvnw -B test-compile
      - name: Test Java
        run: ./mvnw -B test
      - name: No Dirtiness, Java!
        run: git diff --exit-code
