name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Download Dependencies
        run: ./mvnw -B dependency:go-offline
      - name: Build
        run: ./mvnw -B test-compile
      - name: Test
        run: ./mvnw -B test
